"""Criando tabela de documentos e emendas

Revision ID: 48b6c2e97b71
Revises: 
Create Date: 2025-05-29 18:11:45.581973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b6c2e97b71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_emendas',
    sa.Column('num_emenda', sa.Integer(), nullable=False),
    sa.Column('apresentada_por', sa.String(), nullable=False),
    sa.Column('data_apresentacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('vector_store_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_emendas')
    # ### end Alembic commands ###
