"""Create MPV and DocumentEmenda models

Revision ID: 528bbc349558
Revises: 48b6c2e97b71
Create Date: 2025-05-30 10:09:51.059414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528bbc349558'
down_revision: Union[str, None] = '48b6c2e97b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpvs',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ementa', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_emendas', sa.Column('mpv_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document_emendas', 'mpvs', ['mpv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_emendas', type_='foreignkey')
    op.drop_column('document_emendas', 'mpv_id')
    op.drop_table('mpvs')
    # ### end Alembic commands ###
