"""create_initial_models

Revision ID: 6cfa1636fa9e
Revises: 89d0c5d04ce0
Create Date: 2025-06-13 16:29:23.427474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cfa1636fa9e'
down_revision: Union[str, None] = '89d0c5d04ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing tables if they exist
    op.execute('DROP TABLE IF EXISTS emenda_subjects CASCADE')
    op.execute('DROP TABLE IF EXISTS mpv_subjects CASCADE')
    op.execute('DROP TABLE IF EXISTS document_emendas CASCADE')
    op.execute('DROP TABLE IF EXISTS mpvs CASCADE')
    op.execute('DROP TABLE IF EXISTS subjects CASCADE')

    # Create tables
    op.create_table('subjects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('mpvs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('collection_name', sa.String(), nullable=False),
        sa.Column('summary', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('document_emendas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('num_emenda', sa.Integer(), nullable=False),
        sa.Column('apresentada_por', sa.String(), nullable=False),
        sa.Column('data_apresentacao', sa.DateTime(timezone=True), nullable=False),
        sa.Column('chunks_count', sa.Integer(), nullable=True),
        sa.Column('vector_store_name', sa.String(), nullable=True),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('collection_name', sa.String(), nullable=False),
        sa.Column('summary', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('mpv_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['mpv_id'], ['mpvs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('mpv_subjects',
        sa.Column('mpv_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['mpv_id'], ['mpvs.id'], ),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.PrimaryKeyConstraint('mpv_id', 'subject_id')
    )

    op.create_table('emenda_subjects',
        sa.Column('emenda_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['emenda_id'], ['document_emendas.id'], ),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.PrimaryKeyConstraint('emenda_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emenda_subjects')
    op.drop_table('mpv_subjects')
    op.drop_table('document_emendas')
    op.drop_table('mpvs')
    op.drop_table('subjects')
    # ### end Alembic commands ###
